# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT', '0017_auto_20160322_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AGENT.image'),
            preserve_default=False,
        ),
    ]
