# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT', '0019_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_agentis',
            name='specialization',
            field=models.IntegerField(default=0),
        ),
    ]
